Submitting DVO to OCP
redhat-openshift-ecosystem/community-operators-prod pull request #1121
Opened 2022-04-22 18:51 UTC by npecka

### New Submissions

### Operator Description must contain (in order)

The Deployment Validation Operator (DVO) checks deployments and other resources against a curated collection of best practices. 

These best practices focus mainly on ensuring that the applications are fault-tolerant.

DVO will only monitor Kubernetes resources and will not modify them in any way. As an operator it is a continuously running version of the static analysis tool Kube-linter [https://github.com/stackrox/kube-linter]. It will report failed validations via Prometheus, which will allow users of this operator to create alerts based on its results. All the metrics are gauges that will report `1` if the best-practice has failed. The metric will always have three parameters: `name`, `namespace` and `kind`. 

This operator doesn't define any CRDs at the moment. It has been bootstrapped with `operator-sdk` making it possible to add a CRD in the future if required.

2022-04-25 18:14 UTC, framework-automation commented
/merge possible

2022-04-25 19:14 UTC, framework-automation commented
/merge possible

2022-04-26 10:28 UTC, J0zi commented
/test all

2022-04-26 12:16 UTC, J0zi commented
@npecka your operator is in bundle format. Please delete `deployment-validation-operator.package.yaml` file.

2022-04-26 16:46 UTC, framework-automation commented
/merge possible

2022-04-26 18:42 UTC, npecka commented
/retest

2022-04-26 19:13 UTC, framework-automation commented
/merge possible

2022-04-26 19:17 UTC, framework-automation commented
/merge possible

2022-04-27 07:36 UTC, framework-automation commented
/merge possible

2022-04-27 08:10 UTC, mvalarh requested changes

2022-04-27 08:10 UTC, mvalarh commented on operators/deployment-validation-operator/0.2.2/manifests/deploymentvalidationoperator.0.2.2.clusterserviceversion.yaml
> +  replaces: deployment-validation-operator.v0.2.1
@npecka Please remove `replaces:` because you are not replacing any version since there is only `0.2.2`

2022-04-27 08:43 UTC, framework-automation commented
/merge possible

2022-04-27 11:28 UTC, mvalarh requested changes

2022-04-27 11:28 UTC, mvalarh commented on operators/deployment-validation-operator/0.2.2/manifests/deploymentvalidationoperator.0.2.2.clusterserviceversion.yaml
> +  annotations:
This (`annotations`) is duplicate key. Please move line bellow to after line 13

2022-04-27 14:08 UTC, framework-automation commented
/merge possible

2022-04-28 00:04 UTC, mvalarh commented
/test all

2022-04-28 00:56 UTC, framework-automation commented
/merge possible

2022-04-28 05:46 UTC, mvalarh approved these changes

2022-04-28 05:47 UTC, framework-automation commented
/merge possible

2022-04-28 05:47 UTC, merged