turbonomic operator 42.10
redhat-openshift-ecosystem/community-operators-prod pull request #1285
Opened 2022-06-11 02:46 UTC by esara

Signed-off-by: esara <endre.sara@turbonomic.com>

2022-06-11 03:08 UTC, framework-automation commented
/merge possible

2022-06-11 11:05 UTC, esara commented
/retest

2022-06-13 06:38 UTC, mvalarh commented
/test 4.8-deploy-operator-on-openshift

2022-06-13 10:59 UTC, mvalarh commented
@esara can you prepend hostname (docker.io, ....) for turbonomic/t8c-operator:42.10?

2022-06-13 11:56 UTC, esara commented
> @esara can you prepend hostname (docker.io, ....) for turbonomic/t8c-operator:42.10?

@mvalarh this bundle pulls from the redhat registry already - see the image reference - I dont want to change it to dockerhub for the ecosystem operators
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1285/files#diff-e7e97adb8ee2f0ba2f4f268a38079bbc5fca00298845dca9e81a2147214b35fdR58

are you sure that this is a problem?

2022-06-13 13:23 UTC, mvalarh requested changes

2022-06-13 14:52 UTC, esara commented on operators/t8c/42.10.0/t8c-operator.v42.10.0.clusterserviceversion.yaml
> +    containerImage: turbonomic/t8c-operator:42.10
of course, sorry I missed the annotation

2022-06-13 15:15 UTC, framework-automation commented
/merge possible

2022-06-13 15:47 UTC, framework-automation commented
/merge possible

2022-06-13 15:47 UTC, merged